Description: Basic NotebookInstance
Resources:
  BasicNotebookInstance:
    Type: 'AWS::SageMaker::NotebookInstance'
    Properties:
      InstanceType: ml.t2.medium
      RoleArn: !GetAtt ExecutionRole.Arn
  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - comprehend.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonTextractFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        - 'arn:aws:iam::aws:policy/ComprehendFullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
Outputs:  
    NotebookInstanceName:
        Value: !Join 
          - ''
          - - !Sub >-
              https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/
            - !GetAtt BasicNotebookInstance.NotebookInstanceName
